version: '3'
tasks:
  build:
    desc: Build the Spring Boot application
    cmds:
      - ./mvnw clean package -DskipTests
    sources:
      - "src/**/*.java"
    generates:
      - "target/*.jar"

  start:
    desc: Run the Spring Boot application
    cmds:
      - docker compose -f src/main/docker/main.yml up -d
      - ./mvnw spring-boot:run
    interactive: true

  test:
    desc: Run tests
    cmds:
      - ./mvnw test
    sources:
      - "src/**/*.java"
    generates:
      - "target/surefire-reports"

  clean:
    desc: Clean build artifacts
    cmds:
      - ./mvnw clean
    generates:
      - "target/"

  format:
    desc: Format Java code
    cmds:
      - ./mvnw spotless:apply
    sources:
      - "src/**/*.java"

  lint:
    desc: Check Java code formatting
    cmds:
      - ./mvnw checkstyle:check

  dependencies:
    desc: Update project dependencies
    cmds:
      - ./mvnw versions:display-dependency-updates
      - ./mvnw versions:display-plugin-updates

  docker-build:
    desc: Build a Docker image
    cmds:
      - docker build -t my-spring-boot-app .
    sources:
      - "Dockerfile"
      - "src/**"
    generates:
      - "target/*.jar"

  docker-run:
    desc: Run the application in a Docker container
    cmds:
      - docker run --rm -p 8080:8080 my-spring-boot-app
