version: '3.8'

name: bizyhub

services:
  postgresql:
    container_name: bizyhub-postgresql
    image: postgres:13
    networks:
      - bizyhub-network
    environment:
      POSTGRES_USER: bizyhub
      POSTGRES_PASSWORD: bizyhub
      POSTGRES_DB: bizyhub
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "bizyhub", "-d", "bizyhub" ]
      interval: 10s
      retries: 5

  rabbitmq:
    container_name: bizyhub-rabbitmq
    image: rabbitmq:3-management
    networks:
      - bizyhub-network
    environment:
      RABBITMQ_DEFAULT_USER: bizyhub
      RABBITMQ_DEFAULT_PASS: bizyhub
    #      RABBITMQ_DEFAULT_VHOST: bizyhub
    ports:
      - "15672:15672"  # RabbitMQ Management UI
      - "5672:5672"    # RabbitMQ protocol
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      retries: 5

volumes:
  postgresql_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  bizyhub-network:
    driver: bridge
